### ISSUE TITLE
Copy HTML to clipboard erase spaces and tabs

### ISSUE THREAD

**Issue by davide-prade** [APerricone/NppExport#1]
Hi,
the function "Copy HTML to clipboard" erase spaces and tabs.
Can you correct this issue?

Thank you for your effort.

**Comment by APerricone** [comment]
hello,
I am seeing this issue only today, copy HTML to clipboard is made for then paste into a text editor, like word or GMail "new mail",I modified this plug for GMail :)
In what program have you trying to paste in?

**Comment by davide-prade** [comment]
The problem presented itself right on GMail.
Thank you.

**Comment by APerricone** [comment]
Please try new release.

**Comment by davide-prade** [comment]
Now seems ok with 0.2.8 release.

Thank you
